### ISSUE TITLE
Swap Monitor Issue

### ISSUE THREAD

**Issue by netindicium** [MoralisWeb3/demo-apps#9]
Hello there, 

I'm following the instructions on the Swap Monitor, and I was able to get it working, but the daily cumulative stats are not working and this is the error on the console, any idea on what would it be ? 

Thank you, 
A2
![image](https://user-images.githubusercontent.com/37715522/111635363-6bb0fb80-87c5-11eb-95a1-f7d04c95f801.png)

**Comment by jermay** [comment]
Hrm it works for me when I run it locally. Have you added the event plugin and the Cloud Function trigger in your Moralis Server? These are located in the `cloud-functions.js` file. If so, is there data in the `DaiWethSwapVolume60` collection? If not the stats query might not be returning any data.

* The `Swap(address,uint256,uint256,uint256,uint256,address)` event plugin populates the data in the `DaiWethSwaps` collection
* The `Moralis.Cloud.afterSave` trigger adds the stats each time a new swap is saved to that table

This is line 175:
https://github.com/MoralisWeb3/demo-apps/blob/74ca6a8c26da0ddd6e6f8e25a1f2b686a4db3741/swap-monitor/index.js#L175

The `renderStats()` function is called from 2 places:
* `updateStats()` on line 141
* `handleStatsUpdate()` on line 166

Hope that helps.

**Comment by netindicium** [comment]
I have added the Plugin and the Cloud Function as stated on the readme. 
![image](https://user-images.githubusercontent.com/37715522/111713029-c7f33a00-881c-11eb-9235-841686b896aa.png)
![image](https://user-images.githubusercontent.com/37715522/111713035-ca559400-881c-11eb-9101-c3ad58d926d0.png)

I can see the data on the dashboard and on index.html, but no the aggregated stats. 
![image](https://user-images.githubusercontent.com/37715522/111713129-f3762480-881c-11eb-9a82-80d647358fac.png)
![image](https://user-images.githubusercontent.com/37715522/111713148-fc66f600-881c-11eb-9989-4d25164e69c3.png)


Any idea what might be ? 
Thanks.

**Comment by jermay** [comment]
My bad! Thanks for posting the screenshots. This is the problem:

```javascript
const pipeline = [ /* code omitted */ ];
```
Note the `/* code omitted */` comment. I forgot to mention the code for Cloud Functions was supposed to be copied from the `cloud-functions.js` file... not the README. I will update the README to make this clear.

The `pipeline` object is what defines the things to be aggregated. It's a little long to be copying into the docs directly, but if what it's doing is confusing I can add additional explanations to the README. The complexity comes from converting the string values in the table into numbers, which is rather awkward in the MongoDB syntax the queries use.

**Comment by jermay** [comment]
Is this better?
https://github.com/MoralisWeb3/demo-apps/blob/9-bug-swap-trigger-docs/swap-monitor/README.md

I can clarify further if needed.

**Comment by netindicium** [comment]
That fixed it, thanks a lot.  I did had to start a new instance, for some reason the last one would not respond. 

Could you point me in the right direction if I wanted to to tray another token, for example WBTC ?

Thanks again.

**Comment by jermay** [comment]
Cool. I'll close this issue then.

If you wanted to track another swap pair you'd need to:
* Find the contract address for the new pair
* Add a new plugin with the same basic details, but with the contract address of the new pair and a different table name. The Topic and ABI should be the same as it's the same Swap event (just for a different pair)
